# Week 2 — Personal Expenses Analysis

## Session 3 — Grouping, Aggregation, and New Columns

In [12]:
import pandas as pd

expenses_df = pd.read_csv("cleaned-expenses.csv",
                           parse_dates=["Date"]
                          )
expensese_df

        Date        Category   Description      Amount Payment_Method
0 2026-07-01            Food     Groceries   82.500000          Debit
1 2026-07-02  Transportation      Bus pass   45.000000         Credit
2 2026-07-03   Entertainment  Movie ticket   52.214286         Credit
3 2026-07-04            Food    Restaurant   37.250000          Debit
4 2026-07-05       Utilities    Phone bill   65.000000          Debit
5 2026-07-06  Transportation          Taxi   22.500000           Cash
6 2026-07-08         Unknown        Coffee    6.750000        Unknown
7 2026-07-09        Shopping       Clothes  120.000000         Credit

In [13]:
print("Shape: ", expensese_df.shape)
print("Data types: ")
print(expenses_df.dtypes)

Shape:  (8, 5)
Data types:
Date              datetime64[ns]
Category                  object
Description               object
Amount                   float64
Payment_Method            object
dtype: object

## 1. Total Spending by Category

In [14]:
category_totals = (
    expenses_df.groupby("Category")["Amount"].sum().sort_values(ascending=False)
)

category_totals

Category
Shopping          120.000000
Food              119.750000
Transportation     67.500000
Utilities          65.000000
Entertainment      52.214286
Unknown             6.750000
Name: Amount, dtype: float64

## 2. Average Expense by Category

In [15]:
category_averages = (
    expenses_df
    .groupby("Category")["Amount"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

category_averages

Category
Shopping          120.00
Utilities          65.00
Food               59.88
Entertainment      52.21
Transportation     33.75
Unknown             6.75
Name: Amount, dtype: float64

## 3. Count Transactions by Category

In [16]:
category_counts = (
    expenses_df
    .groupby("Category")["Amount"]
    .count()
    .sort_values(ascending=False)
)

category_counts

Category
Food              2
Transportation    2
Entertainment     1
Shopping          1
Unknown           1
Utilities         1
Name: Amount, dtype: int64

## 4. Spending Summary by Category

In [17]:
category_summary = (
    expenses_df
    .groupby("Category")["Amount"]
    .agg(["count", "sum", "mean", "min", "max"])
    .round(2)
    .sort_values("sum", ascending=False)
)

category_summary

                count     sum    mean     min     max
Category
Shopping            1  120.00  120.00  120.00  120.00
Food                2  119.75   59.88   37.25   82.50
Transportation      2   67.50   33.75   22.50   45.00
Utilities           1   65.00   65.00   65.00   65.00
Entertainment       1   52.21   52.21   52.21   52.21
Unknown             1    6.75    6.75    6.75    6.75

## 5. Spending by Payment Method

In [18]:
payment_summary = (
    expenses_df
    .groupby("Payment_Method")["Amount"]
    .agg(["count", "sum", "mean"])
    .round(2)
    .sort_values("sum", ascending=False)
)

payment_summary

                count     sum   mean
Payment_Method
Credit              3  217.21  72.40
Debit               3  184.75  61.58
Cash                1   22.50  22.50
Unknown             1    6.75   6.75

## 6. Create a Month Column

In [19]:
expenses_df["Month"] = expenses_df["Date"].dt.month_name()

expenses_df[["Date", "Month"]]

        Date Month
0 2026-07-01  July
1 2026-07-02  July
2 2026-07-03  July
3 2026-07-04  July
4 2026-07-05  July
5 2026-07-06  July
6 2026-07-08  July
7 2026-07-09  July

## 7. Create a Needs or Wants Column

In [20]:
needs_categories = ["Food", "Transportation", "Utilities"]

expenses_df["Needs_or_Wants"] = expenses_df["Category"].apply(
    lambda category: "Need" if category in needs_categories else "Want"
)

expenses_df[["Category", "Needs_or_Wants"]]

         Category Needs_or_Wants
0            Food           Need
1  Transportation           Need
2   Entertainment           Want
3            Food           Need
4       Utilities           Need
5  Transportation           Need
6         Unknown           Want
7        Shopping           Want

## 8. Create a Large Expense Column

In [21]:
expenses_df["Large_Expense"] = expenses_df["Amount"].apply(
    lambda amount: "Yes" if amount >= 75 else "No"
)

expenses_df[["Description", "Amount", "Large_Expense"]]

    Description      Amount Large_Expense
0     Groceries   82.500000           Yes
1      Bus pass   45.000000            No
2  Movie ticket   52.214286            No
3    Restaurant   37.250000            No
4    Phone bill   65.000000            No
5          Taxi   22.500000            No
6        Coffee    6.750000            No
7       Clothes  120.000000           Yes