# Week 2 — Personal Expenses Analysis

## Session 1 — Load and Inspect Expense Data

In [12]:
import pandas as pd

expense_data = {
    "Date": [
        "2026-07-01",
        "2026-07-02",
        "2026-07-03",
        "2026-07-04",
        "2026-07-05",
        "2026-07-06",
        "2026-07-07",
        "2026-07-08"
    ],
    "Category": [
        "Food",
        "Transportation",
        "Entertainment",
        "Food",
        "Utilities",
        "Transportation",
        "Shopping",
        "Food"
    ],
    "Description": [
        "Groceries",
        "Bus pass",
        "Movie ticket",
        "Restaurant",
        "Phone bill",
        "Taxi",
        "Clothes",
        "Coffee"
    ],
    "Amount": [
        82.50,
        45.00,
        18.00,
        37.25,
        65.00,
        22.50,
        120.00,
        6.75
    ],
    "Payment_Method": [
        "Debit",
        "Credit",
        "Credit",
        "Debit",
        "Debit",
        "Cash",
        "Credit",
        "Cash"
    ]
}

expenses_df = pd.DataFrame(expense_data)

expenses_df

         Date        Category   Description  Amount Payment_Method
0  2026-07-01            Food     Groceries   82.50          Debit
1  2026-07-02  Transportation      Bus pass   45.00         Credit
2  2026-07-03   Entertainment  Movie ticket   18.00         Credit
3  2026-07-04            Food    Restaurant   37.25          Debit
4  2026-07-05       Utilities    Phone bill   65.00          Debit
5  2026-07-06  Transportation          Taxi   22.50           Cash
6  2026-07-07        Shopping       Clothes  120.00         Credit
7  2026-07-08            Food        Coffee    6.75           Cash

## 1. Inspect the Dataset

In [13]:
print("Number of rows:", expenses_df.shape[0])
print("Number of columns:", expenses_df.shape[1])
print("\nColumns names:", expenses_df.columns.tolist())
print(expenses_df.dtypes)

Number of rows: 8
Number of columns: 5

Columns names: ['Date', 'Category', 'Description', 'Amount', 'Payment_Method']
Date               object
Category           object
Description        object
Amount            float64
Payment_Method     object
dtype: object

## 2. Convert the Date Column

In [14]:
expenses_df["Date"] = pd.to_datetime(expenses_df["Date"])

print(expenses_df.dtypes)

Date              datetime64[ns]
Category                  object
Description               object
Amount                   float64
Payment_Method            object
dtype: object

## 3. Dataset Information and Summary

In [16]:
expenses_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            8 non-null      datetime64[ns]
 1   Category        8 non-null      object
 2   Description     8 non-null      object
 3   Amount          8 non-null      float64
 4   Payment_Method  8 non-null      object
dtypes: datetime64[ns](1), float64(1), object(3)
memory usage: 452.0+ bytes

In [17]:
expenses_df.describe()

                      Date      Amount
count                    8    8.000000
mean   2026-07-04 12:00:00   49.625000
min    2026-07-01 00:00:00    6.750000
25%    2026-07-02 18:00:00   21.375000
50%    2026-07-04 12:00:00   41.125000
75%    2026-07-06 06:00:00   69.375000
max    2026-07-08 00:00:00  120.000000
std                    NaN   37.831393

## 4. Check for Missing Values

In [18]:
expenses_df.isna().sum()

Date              0
Category          0
Description       0
Amount            0
Payment_Method    0
dtype: int64

## 5. View the First and Last Records

In [19]:
display(expenses_df.head(3))
display(expenses_df.tail(3))

        Date        Category   Description  Amount Payment_Method
0 2026-07-01            Food     Groceries    82.5          Debit
1 2026-07-02  Transportation      Bus pass    45.0         Credit
2 2026-07-03   Entertainment  Movie ticket    18.0         Credit

        Date        Category Description  Amount Payment_Method
5 2026-07-06  Transportation        Taxi   22.50           Cash
6 2026-07-07        Shopping     Clothes  120.00         Credit
7 2026-07-08            Food      Coffee    6.75           Cash

## 6. Inspect Unique Values

In [20]:
print("Categories:")
print(expenses_df["Category"].unique())

print("\nPayment methods:")
print(expenses_df["Payment_Method"].unique())

Categories:
['Food' 'Transportation' 'Entertainment' 'Utilities' 'Shopping']

Payment methods:
['Debit' 'Credit' 'Cash']

## 7. Count Values in Categorical Columns

In [21]:
print("Category counts:")
print(expenses_df["Category"].value_counts())

print("\nPayment method counts:")
print(expenses_df["Payment_Method"].value_counts())

Category counts:
Category
Food              3
Transportation    2
Entertainment     1
Utilities         1
Shopping          1
Name: count, dtype: int64

Payment method counts:
Payment_Method
Debit     3
Credit    3
Cash      2
Name: count, dtype: int64

## 8. Basic Amount Analysis

In [22]:
print("Total spending:", expenses_df["Amount"].sum())
print("Average expense:", expenses_df["Amount"].mean())
print("Highest expense:", expenses_df["Amount"].max())
print("Lowest expense:", expenses_df["Amount"].min())

Total spending: 397.0
Average expense: 49.625
Highest expense: 120.0
Lowest expense: 6.75

## 9. Find the Highest Expense Record

In [23]:
highest_expensese_index = expenses_df["Amount"].idxmax()
highest_expense = expenses_df.loc[highest_expensese_index]

highest_expense

Date              2026-07-07 00:00:00
Category                     Shopping
Description                   Clothes
Amount                          120.0
Payment_Method                 Credit
Name: 6, dtype: object

## 10. Session 1 Summary

In [24]:
print("Dataset shape:", expenses_df.shape)
print("Missing values:", expenses_df.isna().sum().sum())
print("Total spending:", expenses_df["Amount"].sum())
print("Average expense:", round(expenses_df["Amount"].mean(), 2))
print("Most common category:", expenses_df["Category"].mode()[0])
print("Highest expense:", expenses_df["Amount"].max())

Dataset shape: (8, 5)
Missing values: 0
Total spending: 397.0
Average expense: 49.62
Most common category: Food
Highest expense: 120.0