# Week 2 — Personal Expenses Analysis

## Session 2 — Clean Missing and Incorrect Values

In [1]:
import pandas as pd
import numpy as np

expense_data = {
    "Date": [
        "2026-07-01",
        "2026-07-02",
        "2026-07-03",
        "2026-07-04",
        "2026-07-05",
        "2026-07-06",
        "2026-07-06",
        "2026-07-08",
        "2026-07-09"
    ],
    "Category": [
        "Food",
        "transportation",
        "Entertainment",
        "Food ",
        "Utilities",
        "Transportation",
        "Transportation",
        None,
        "Shopping"
    ],
    "Description": [
        "Groceries",
        "Bus pass",
        "Movie ticket",
        "Restaurant",
        "Phone bill",
        "Taxi",
        "Taxi",
        "Coffee",
        "Clothes"
    ],
    "Amount": [
        82.50,
        45.00,
        np.nan,
        37.25,
        65.00,
        22.50,
        22.50,
        -6.75,
        120.00
    ],
    "Payment_Method": [
        "Debit",
        "Credit",
        "credit",
        "Debit ",
        "Debit",
        "Cash",
        "Cash",
        None,
        "Credit"
    ]
}

expenses_df = pd.DataFrame(expense_data)

expenses_df

         Date        Category   Description  Amount Payment_Method
0  2026-07-01            Food     Groceries   82.50          Debit
1  2026-07-02  transportation      Bus pass   45.00         Credit
2  2026-07-03   Entertainment  Movie ticket     NaN         credit
3  2026-07-04           Food     Restaurant   37.25         Debit
4  2026-07-05       Utilities    Phone bill   65.00          Debit
5  2026-07-06  Transportation          Taxi   22.50           Cash
6  2026-07-06  Transportation          Taxi   22.50           Cash
7  2026-07-08            None        Coffee   -6.75           None
8  2026-07-09        Shopping       Clothes  120.00         Credit

## 1. Inspect the Messy Dataset

In [4]:
print("Dataset shape", expenses_df.shape)
print("\nMissing values:")
print(expenses_df.isna().sum())
print("\nDuplicate rows:")
print(expenses_df.duplicated().sum())
print("\nData types:")
print(expenses_df.dtypes)

Dataset shape (9, 5)

Missing values:
Date              0
Category          1
Description       0
Amount            1
Payment_Method    1
dtype: int64

Duplicate rows:
1

Data types:
Date               object
Category           object
Description        object
Amount            float64
Payment_Method     object
dtype: object

## 2. Remove Duplicate Rows

In [8]:
expenses_df = expenses_df.drop_duplicates().copy()

print("New shape:", expenses_df.shape)
print("Duplicate rows remaining:", expenses_df.duplicated().sum())

New shape: (8, 5)
Duplicate rows remaining: 0

## 3. Clean Text Values

In [9]:
expenses_df["Category"] = expenses_df["Category"].str.strip().str.title()
expenses_df["Payment_Method"] = expenses_df["Payment_Method"].str.strip().str.title()

print("Categories:")
print(expenses_df["Category"].unique())

print("\nPayment methods:")
print(expenses_df["Payment_Method"].unique())

Categories:
['Food' 'Transportation' 'Entertainment' 'Utilities' 'Unknown' 'Shopping']

Payment methods:
['Debit' 'Credit' 'Cash' 'Unknown']

## 4. Fill Missing Text Values

In [10]:
expenses_df["Category"] = expenses_df["Category"].fillna("Unknown")
expenses_df["Payment_Method"] = expenses_df["Payment_Method"].fillna("Unknown")

print(expenses_df.isna().sum())

Date              0
Category          0
Description       0
Amount            1
Payment_Method    0
dtype: int64

## 5. Fill the Missing Amount

In [11]:
average_amount = expenses_df["Amount"].mean()

expenses_df["Amount"] = expenses_df["Amount"].fillna(average_amount)

print("Average used: ", round(average_amount, 2))
print("Missing values:")
print(expenses_df.isna().sum())

Average used:  52.21
Missing values:
Date              0
Category          0
Description       0
Amount            0
Payment_Method    0
dtype: int64

## 6. Find Invalid Amounts

In [12]:
invalid_amounts = expenses_df[expenses_df["Amount"] <= 0]

print(invalid_amounts)

         Date Category Description  Amount Payment_Method
7  2026-07-08  Unknown      Coffee   -6.75        Unknown

## 7. Correct the Invalid Amount

In [13]:
expenses_df.loc[expenses_df["Amount"] < 0, "Amount"] = (
    expenses_df.loc[expenses_df["Amount"] < 0, "Amount"].abs()
)

expenses_df

         Date        Category   Description      Amount Payment_Method
0  2026-07-01            Food     Groceries   82.500000          Debit
1  2026-07-02  Transportation      Bus pass   45.000000         Credit
2  2026-07-03   Entertainment  Movie ticket   52.214286         Credit
3  2026-07-04            Food    Restaurant   37.250000          Debit
4  2026-07-05       Utilities    Phone bill   65.000000          Debit
5  2026-07-06  Transportation          Taxi   22.500000           Cash
7  2026-07-08         Unknown        Coffee    6.750000        Unknown
8  2026-07-09        Shopping       Clothes  120.000000         Credit

In [14]:
print("Invalid amounts remaining:")
print((expenses_df["Amount"] <= 0).sum())

Invalid amounts remaining:
0

## 8. Convert the Date Column

In [15]:
expenses_df["Date"] = pd.to_datetime(expenses_df["Date"])

print(expenses_df.dtypes)

Date              datetime64[ns]
Category                  object
Description               object
Amount                   float64
Payment_Method            object
dtype: object

## 9. Reset the Index

In [17]:
expenses_df = expenses_df.reset_index(drop=True)

expenses_df

        Date        Category   Description      Amount Payment_Method
0 2026-07-01            Food     Groceries   82.500000          Debit
1 2026-07-02  Transportation      Bus pass   45.000000         Credit
2 2026-07-03   Entertainment  Movie ticket   52.214286         Credit
3 2026-07-04            Food    Restaurant   37.250000          Debit
4 2026-07-05       Utilities    Phone bill   65.000000          Debit
5 2026-07-06  Transportation          Taxi   22.500000           Cash
6 2026-07-08         Unknown        Coffee    6.750000        Unknown
7 2026-07-09        Shopping       Clothes  120.000000         Credit

## 10. Final Data Quality Check

In [18]:
print("Dataset shape:", expenses_df.shape)
print("Duplicate rows:", expenses_df.duplicated().sum())
print("Missing values:", expenses_df.isna().sum().sum())
print("Invalid amounts:", (expenses_df["Amount"] <= 0).sum())

print("\nData types:")
print(expenses_df.dtypes)

Dataset shape: (8, 5)
Duplicate rows: 0
Missing values: 0
Invalid amounts: 0

Data types:
Date              datetime64[ns]
Category                  object
Description               object
Amount                   float64
Payment_Method            object
dtype: object